### ISSUE TITLE
reconstruction_superres.py

### ISSUE THREAD

**Issue by PierceLovesee** [DISHDevEx/leto#30]
Model is not being specified in upsample method.

Traceback (most recent call last):
  File "/projects/leto/reconstruction/superres/reconstruction_superres.py", line 112, in <module>
    superres_video(method_args, s3_args)
  File "/projects/leto/reconstruction/superres/reconstruction_superres.py", line 85, in superres_video
    result = model.upsample(frame)
cv2.error: OpenCV(4.8.0) /io/opencv_contrib/modules/dnn_superres/src/dnn_superres.cpp:115: error: (-2:Unspecified error) Model not specified. Please set model via setModel(). in function 'upsample'

**Comment by vinayakSharm** [comment]
can you pls paste the running command you used, in order to recreate this issue.

**Comment by vinayakSharm** [comment]
unable to recreate issue -> closing

**Comment by vinayakSharm** [comment]
closed
